# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 15:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=11)),
                ('ticket_type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=7)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('title', models.CharField(help_text='Titles can have a maximum of 75 characters.', max_length=75)),
                ('description', models.TextField(help_text='Descriptions can have a maximum of 2,000 characters.', max_length=2000)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
