# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_added',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_edited',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
