# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190706_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='ticket_status',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', help_text='Descriptions can have a maximum of 2,000 characters.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', help_text='Titles can have a maximum of 75 characters.', max_length=75),
        ),
    ]
