# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190711_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_commented',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
