# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190711_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_commented',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', help_text='Comments can have a maximum of 2,000 characters.', max_length=2000),
        ),
    ]
