# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190711_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Comments can have a maximum of 2,000 characters.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=75),
        ),
    ]
