# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190712_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpvoteBug',
            new_name='Upvote',
        ),
    ]
