# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20190718_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='ticket_status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'In Progress'), ('3', 'Closed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('1', 'Bug'), ('2', 'Feature')], max_length=1),
        ),
    ]
