# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20190718_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('1', 'Bug'), ('2', 'Feature')], max_length=7, unique=True),
        ),
    ]
