# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20190718_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], max_length=7, unique=True),
        ),
    ]
