# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20190727_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
