# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_imgs/default.png', upload_to='profile_imgs'),
        ),
    ]
