# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190706_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_donated',
            field=models.IntegerField(default=0),
        ),
    ]
