# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 21:11
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_total_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
